language: php
php:
- 5.4
- 5.5
- 5.6
env:
  global:
  - GIT_NAME: "Gitlab-CI Couscous doc"
  - GH_REF: github.com/BilelJegham/Gitlab-CI
  - secure: nfPXWJ5i5Ykos6W/LdkfrvOYN0IJDEJ2JVBtKa3cGiRrgEWzrGgfrZi17Ar61kZmaH5t0UbGAqANYuYxhb7UGg5h2wPAx4zjVetk/7IBpkg7jecDrldRR4IgKYzPSbVsPfOek1+C0cYtSg9oEsHfUHTBrCymiGcKZ95EcsA8SBwMrCwCVAKtKIjZFmHm66IQ3fhhtu9TKZLqgW1EWuVcnJgwI5YhsZX61u0emSrAJTIW8DPDU0XtAR1D0T1kRbhsF+ruPnszm60kEolDnymfGg8P0hlAccQVaacC7xfiqredvwopjTsNXWE1woVAxj+OGs95Eem03ym8O8ZE7HeAgHe65SwcfFr/BG4UTuvZo9MfPliSu2U30j0B0kkeqxGtGpIO3z5Wg1U4ydiF8C6wP6netlKoSxj+drNC6N9aF0TRVQVzw7/DtvH9GNaEMEs0IZ6aucETnTr5D9kcYSmAuh/UlvshRp8rPkrIHSg4PCUwLI3+XCiiCqWbTnJwD1H7Nqr6jggL1tJBeuqtgv3ekGrgW7FMl9pfdCk9fjK63cORLOkF1Y16ai+p1Li7x8oVGycUKNHaOEJC47vCWs59L5lAvWalthwB6+5xkXPjqR/Ve4vE7xKmc28+cPIy05OIrDC6X1eHrcyOfzOBAWiFz2judWJAdZgeekkleNYou2I=
before_script:
- composer install --no-progress
script:
- phpunit

after_success:
- vendor/bin/couscous travis-auto-deploy
